[package]
name = "minigolf"
version = "0.1.0"
authors = ["Aatu Hieta <aatu@hieta.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mela = { path = "../../mela", features = ["2d"] }
num = "0.3.0"